commits: https://github.com/kidlj/kidlj.github.io/commits/master/

defaults:

- scope: 
    path: ""
    type: "posts"
  values:
    layout: "post"

- scope:
    path: ""
    type: "wiki"
  values:
    layout: "wiki"

collections:
  wiki:
      output: true
      permalink: /wiki/:name.html
