commits: https://github.com/kidlj/kidlj.github.io/commits/master/

defaults:

- scope: 
    path: ""
    type: "posts"
  values:
    layout: "post"

- scope:
    path: ""
    type: "wiki"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "music"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "read"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "movie"
  values:
    layout: "wiki"

collections:
  wiki:
    output: true
    permalink: /wiki/:name.html
  music:
    output: true
    permalink: /music/:name.html
  read :
    output: true
    permalink: /read/:name.html
  movie:
    output: true
    permalink: /movie/:name.html
