commits: https://github.com/kidlj/site/commits/master/

plugins: [jekyll-paginate]
permalink: /blog/:year-:month-:day-:title.html
paginate: 10
paginate_path: "blog/page/:num"

defaults:

- scope: 
    path: ""
    type: "posts"
  values:
    layout: "post"

- scope:
    path: ""
    type: "wiki"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "code"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "read"
  values:
    layout: "read"

collections:
  wiki:
    output: true
    permalink: /wiki/:name.html
  code:
    output: true
    permalink: /code/:name.html
  read:
    output: true
    permalink: /read/:name.html
