commits: https://github.com/kidlj/kidlj.github.io/commits/master/

defaults:

- scope: 
    path: ""
    type: "posts"
  values:
    layout: "post"

- scope:
    path: ""
    type: "wiki"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "code"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "read"
  values:
    layout: "wiki"

collections:
  wiki:
    output: true
    permalink: /wiki/:name.html
  code:
    output: true
    permalink: /code/:name.html
  read :
    output: true
    permalink: /read/:name.html
